/* Autogenerated with kurento-module-creator */

#ifndef __VIOLENCE_DETECTION_MODULE_OPENCV_IMPL_HPP__
#define __VIOLENCE_DETECTION_MODULE_OPENCV_IMPL_HPP__

#include <OpenCVProcess.hpp>
#include "ViolenceDetectionModule.hpp"
#include <EventHandler.hpp>

namespace kurento
{
namespace module
{
namespace violencedetectionmodule
{

class ViolenceDetectionModuleOpenCVImpl : public virtual OpenCVProcess
{

public:

  ViolenceDetectionModuleOpenCVImpl ();

  virtual ~ViolenceDetectionModuleOpenCVImpl() = default;

  virtual void process (cv::Mat &mat);

};

} /* violencedetectionmodule */
} /* module */
} /* kurento */

#endif /*  __VIOLENCE_DETECTION_MODULE_OPENCV_IMPL_HPP__ */
