/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include <ViolenceDetectionModuleImplFactory.hpp>
#include "ViolenceDetectionModuleImpl.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>
#include "MediaPipelineImpl.hpp"

#define GST_CAT_DEFAULT kurento_violence_detection_module_impl
GST_DEBUG_CATEGORY_STATIC (GST_CAT_DEFAULT);
#define GST_DEFAULT_NAME "KurentoViolenceDetectionModuleImpl"

namespace kurento
{
namespace module
{
namespace violencedetectionmodule
{

ViolenceDetectionModuleImpl::ViolenceDetectionModuleImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline) : OpenCVFilterImpl (config, std::dynamic_pointer_cast<MediaPipelineImpl> (mediaPipeline))

{
}

MediaObjectImpl *
ViolenceDetectionModuleImplFactory::createObject (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline) const
{
  return new ViolenceDetectionModuleImpl (config, mediaPipeline);
}

ViolenceDetectionModuleImpl::StaticConstructor ViolenceDetectionModuleImpl::staticConstructor;

ViolenceDetectionModuleImpl::StaticConstructor::StaticConstructor()
{
  GST_DEBUG_CATEGORY_INIT (GST_CAT_DEFAULT, GST_DEFAULT_NAME, 0,
                           GST_DEFAULT_NAME);
}

} /* violencedetectionmodule */
} /* module */
} /* kurento */
