/* Autogenerated with kurento-module-creator */

#include "ViolenceDetectionModuleOpenCVImpl.hpp"
#include <KurentoException.hpp>

namespace kurento
{
namespace module
{
namespace violencedetectionmodule
{

ViolenceDetectionModuleOpenCVImpl::ViolenceDetectionModuleOpenCVImpl ()
{
}

/*
 * This function will be called with each new frame. mat variable
 * contains the current frame. You should insert your image processing code
 * here. Any changes in mat, will be sent through the Media Pipeline.
 */
void ViolenceDetectionModuleOpenCVImpl::process (cv::Mat &mat)
{
  // FIXME: Implement this
   cv::Point textOrg(100, 100);
   putText( mat, "Hello from Meetrix.IO", textOrg, 1, 2, cv::Scalar(0, 0, 0) );
}



} /* violencedetectionmodule */
} /* module */
} /* kurento */
