/* Autogenerated with kurento-module-creator */

#include "ViolenceDetectionModuleOpenCVImpl.hpp"
#include <KurentoException.hpp>

namespace kurento
{
namespace module
{
namespace violencedetectionmodule
{

ViolenceDetectionModuleOpenCVImpl::ViolenceDetectionModuleOpenCVImpl ()
{
}

/*
 * This function will be called with each new frame. mat variable
 * contains the current frame. You should insert your image processing code
 * here. Any changes in mat, will be sent through the Media Pipeline.
 */
std::vector<cv::Mat> gray_video;
std::vector<cv::Mat> frames;
std::vector<cv::Mat> flows;

void ViolenceDetectionModuleOpenCVImpl::process (cv::Mat &mat)
{
  // FIXME: Implement this
  cv::Mat frame;
  cv::resize(mat, frame, cv::Size(224, 224), CV_INTER_AREA);
  cv::cvtColor(frame, frame, cv::COLOR_BGR2RGB);
  frames.push_back(frame);


}



} /* violencedetectionmodule */
} /* module */
} /* kurento */
